import { createSlice } from '@reduxjs/toolkit';

const translationSlice = createSlice({
  name: 'translation',
  initialState: {
    language: 'en', 
    translations: {
      "en": {
        "home" : "Home",
        "store" : "Store",
        "about" : "About Us",
        "brand" : "International brands",
        "blog" : "Blog",
        "contact" : "Contact Us",
        "new" : "What's new",
        "discover" : "Discover everything new",
        "detailsbtn" : "details",
        "links" : "Important links",
        "shipping" : "Shipping Information To ensure your purchases arrive safely, please be sure to provide",
        "private" : "Private Policy",
        "cookies" : "cookies Policy",
        "info" : "Delivery Information",
        "contactP" : "Contact us for any inquiries or assistance you require, we are here to provide support and advice",
        "subscribe" : "Subscribe to AdobeXD via Email",
        "login" : "Sign In",
        "register" : "Sign Up",
        "newhere" : "New Here ?",
        "welcome" : "we are glad you visited our website",
        "oneofus" : "One Of Us",
        "interested" : "You may also be interested in ",
        "track" : "Track Order" ,
        "orders" : "orders",
        "logout" : "logout" ,
        "placed" : "Placed",
        "process" : "Processing",
        "shipped" : "Shipped",
        "deliver" : "Delivered",
        "aboutParagraph" : "Your trusted partner for your health needs. We provide high-quality products and distinguished service to ensure your health and comfort. Get to know us and how we care for you",
        "buyabout" : "Buy Now",
        "accuracy" : "High accuracy",
        "accuracyParagraph" : "High accuracy guarantees you an excellent shopping experience on our e-commerce website, as we always strive to ensure the quality of our products and the accuracy of our services",
        "awards" : "awards",
        "winners" : "Winners of multiple awards, we guarantee you an exceptional shopping experience on our e-commerce website, as our  services and products are distinguished by excellence and recognition.",
        "friends" : "Friends of yours",
        "friendParagraph" : "We are your friends' place in the world of e-commerce, as we provide you with products and services that give you a unique and reliable shopping experience",
        "Fastshipping" : "Fast shipping",
        "offer" : "We offer a fast shipping service that makes your products reach you as quickly as possible, so you can enjoy an immediate and comfortable shopping experience" ,
        "addresscontact" : "Address",
        "addressdescontact" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M).",
        "addressdescontacttwo" : "Tetouan: Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "hours" : "Working hours",
        "day" : "Monday to Friday: 7am - 7pm",
        "weekend" : "Weekend: 10am - 5pm" , 
        "phonenumber" : "phone number",
        "email" : "Email",
        "contactform" : "You are always welcome to contact us with questions, and inquiry about our services.",
        "submitcontact" : "submit message",
        "categories" : "Categories",
        "magasin" : "Store",
        "learnmore" : "Learn more through our product categories",

      },
      "fr": {
        "home" : "Maison",
        "store" : "Magasin",
        "about" : "A propos de nous",
        "brand" : "Marques internatio",
        "blog" : "Blog",
        "contact" : "Contactez nous",
        "new" : "quoi de neuf",
        "discover" : "Découvrez tout ce qui est nouveau",
        "detailsbtn" : "détails",
        "links" : "Liens importants",
        "shipping" : "Informations d'expédition Pour garantir que vos achats arrivent sans problème, assurez-vous de fournir",
        "private" : "Politique privée",
        "cookies" : "Politique de cookies",
        "info" : "Informations sur la livraison",
        "contactP" : "Contactez-nous pour toute demande de renseignements ou d'assistance dont vous avez besoin, nous sommes là pour vous fournir soutien et conseils",
        "subscribe" : "Abonnez-vous à AdobeXD par e-mail",
        "login" : "se connecter",
        "register" : "registre",
        "newhere" : "Nouveau ici ?",
        "welcome" : "Bienvenue, nous sommes heureux que vous ayez visité notre site Web",
        "oneofus" : "Un de nous",
        "interested" : "Vous pourriez également être intéressé par",
        "track" : "suivre les commandes",
        "orders" : "ordres",
        "logout" : "Se déconnecter" ,
        "placed" : "mis",
        "process" : "Traitement",
        "shipped" : "Expédié",
        "deliver" : "Livré",
        "aboutParagraph" : "Votre partenaire de confiance pour vos besoins en santé. Nous fournissons des produits de haute qualité et un service distingué pour assurer votre santé et votre confort. Apprenez à nous connaître et comment nous prenons soin de vous",
        "buyabout" : "Acheter maintenant",
        "accuracy" : "Haute précision",
        "accuracyParagraph" : "Une haute précision vous garantit une excellente expérience d'achat sur notre site e-commerce, car nous nous efforçons toujours de garantir la qualité de nos produits et l'exactitude de nos services",
        "awards" : "Prix",
        "winners" : "Gagnants de multiples prix, nous vous garantissons une expérience d'achat exceptionnelle sur notre site e-commerce, car nos services et produits se distinguent par l'excellence et la reconnaissance.",
        "friends" : "Vos amis",
        "friendParagraph" : "Nous sommes la place de vos amis dans le monde du commerce électronique, car nous vous proposons des produits et services qui vous offrent une expérience d'achat unique et fiable.",
        "Fastshipping" : "Expédition rapide",
        "offer" : "Nous offrons un service d'expédition rapide qui permet à vos produits de vous parvenir le plus rapidement possible, afin que vous puissiez profiter d'une expérience d'achat immédiate et confortable.",
        "addresscontact" : "l'adresse",
        "addressdescontact" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M).",
        "addressdescontacttwo" : "Tetouan: Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "hours" : "Heures de travail",
        "day" : "Du lundi au vendredi : 7h - 19h",
        "weekend" : "Weekend: 10am - 5pm" , 
        "phonenumber" : "numéro de téléphone",
        "email" : "Email",
        "contactform" : "Vous êtes toujours invités à nous contacter pour toute question ou demande de renseignements sur nos services.",
        "submitcontact" : "soumettre un message",
        "categories" : "catégories",
        "magasin" : "Magasin",
        "learnmore" : "Apprenez-en davantage à travers nos catégories de produits",

      },
      "ar": {
        "home" : "الرئيسيه",
        "store" : "المتجر",
        "about" : "معلومات عنا",
        "brand" : "ماركات عالمية",
        "blog" : "المدونه",
        "contact" : "تواصل معنا",
        "new" : "ما الجديد",
        "new" : "اكتشف كل ما هو جديد",
        "detailsbtn" : "تفاصيل",
        "links" : "روابط مهمه",
        "shipping" : "معلومات الشحن لضمان وصول مشترياتك بأمان، يرجى التأكد من تقديمها",
        "private" : "سياسة خاصة",
        "cookies" : "اتفاقيات تعريف الارتباط",
        "info" : "معلومات التوصيل",
        "contactP" : "اتصل بنا للحصول على أية استفسارات أو مساعدة تحتاجها، فنحن هنا لتقديم الدعم والمشورة",
        "subscribe" : "اشترك في AdobeXD عبر البريد الإلكتروني",
        "login" : "تسجيل دخول",
        "register" : "انشاء حساب",
        "newhere" : "جديد هنا ؟",
        "welcome" : "مرحباً بك، نحن سعداء بزيارتك لموقعنا",
        "oneofus" : "واحد منا",
        "interested" : "قد تكون أيضا مهتما ب",
        "track" : "تتبع الطلب",
        "orders" : "طلبات",
        "logout" : "تسجيل خروج" ,
        "placed" : "تم الطلب",
        "process" : "معالجه",
        "shipped" : "تم الشحن",
        "deliver" : "تسليم",
        "aboutParagraph" : "شريكك الموثوق به لتلبية احتياجاتك الصحية. نحن نقدم منتجات عالية الجودة وخدمة متميزة لضمان صحتك وراحتك. تعرف علينا وكيف نهتم بك",
        "buyabout" : "اشترى الان",
        "accuracy" : "دقة عالية",
        "accuracyParagraph" : "الدقة العالية تضمن لك تجربة تسوق ممتازة على موقع التجارة الإلكترونية الخاص بنا، كما نسعى دائمًا لضمان جودة منتجاتنا ودقة خدماتنا",
        "awards" :" مكافأت" ,
        "winners" : "الفائزون بجوائز متعددة، نضمن لكم تجربة تسوق استثنائية على موقعنا للتجارة الإلكترونية، حيث تتميز خدماتنا ومنتجاتنا بالتميز والتقدير",
        "friends" : "أصدقاء لك",
        "friendParagraph" : "نحن مكان أصدقائك في عالم التجارة الإلكترونية حيث نقدم لك منتجات وخدمات تمنحك تجربة تسوق فريدة وموثوقة",
        "Fastshipping" : "شحن سريع",
        "offer" : "نحن نقدم خدمة شحن سريعة تجعل منتجاتك تصل إليك في أسرع وقت ممكن، لتستمتع بتجربة تسوق فورية ومريحة",
        "addresscontact" : "العنوان",
        "addressdescontact" : "LAAYOUNE : MADINAT EL WAHDA BLOC B NR 91 LAAYOUNE (M).",
        "addressdescontacttwo" : "Tetouan: Mezanine bloc B Bureau n 4 BOROUJ 16 Avenue des Far N° 873 Tétouan",
        "hours" : "ساعات العمل",
        "day" : "من الاثنين إلى الجمعة: 7 صباحًا - 7 مساءً",
        "weekend" : " نهاية الأسبوع: 10 صباحًا - 5 مساءً",
        "phonenumber" : "رقم الهاتف",
        "email" : "بريد الكتروني",
        "contactform" : "نرحب دائمًا باتصالك بنا لطرح الأسئلة والاستفسار عن خدماتنا.",
        "submitcontact" : "ارسال",
        "categories" : "فئات" ,
        "magasin" : "متجر",
        "learnmore" :"تعلم المزيد من خلال فئات منتجاتنا",
      }
    },
  },
  reducers: {
    setLanguage: (state, action) => {
      state.language = action.payload;
    },
  },
});

export const { setLanguage } = translationSlice.actions;

export const selectLanguage = (state) => state.translation.language;
export const selectTranslations = (state) => state.translation.translations;

export default translationSlice.reducer;
